{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-web-chart.fullname" . }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
        - path: {{ (index .Values.ingress.hosts 0).paths 0).path }}
          pathType: {{ (index .Values.ingress.hosts 0).paths 0).pathType }}
          backend:
            service:
              name: {{ include "flask-web-chart.fullname" . }}
              port:
                number: {{ .Values.service.port }}
{{- end }}
